os: osx
language: swift
osx_image: xcode11.3
xcode_project: CountriesSwiftUI.xcodeproj
xcode_scheme: CountriesSwiftUI
xcode_sdk: iphonesimulator13.2
xcode_destination: platform=iOS Simulator,OS=13.3,name=iPhone 8
after_success:
  - bash <(curl -s https://codecov.io/bash)